#!/bin/bash
# Get video info for KMediafactory
# Copyright (C) 2007 by Petri Damsten - GPL-2
# Usage:
# kmf_info /media/movies/movie.mpg

SCRIPTS=`dirname $0`
. $SCRIPTS/tools

FFMPEG=`check_executable "ffmpeg" "ffmpeg"`

OUTPUT=`$FFMPEG -i "$1" 2>&1`
VIDEO=$(echo "$OUTPUT" | grep Stream | grep "Video:")
AUDIO=$(echo "$OUTPUT" | grep "Stream #0.1" | grep "Audio")
ASPECT=$(echo "$VIDEO" | awk -FDAR '{print $2}' | awk -F' ' '{print $1}' | sed 's^]^^g' | sed 's^,^^g')
RESOLUTION=$(echo "$VIDEO" | awk -FVideo: '{print $2}' | awk '{print $3}')
if [ "$ASPECT" = "4:3" ] ; then
    ASPECT=0
else
    ASPECT=1
fi
HRS=$(echo "$OUTPUT" | grep "Duration:" | awk -F: '{print $2}')
MINS=$(echo "$OUTPUT" | grep "Duration:" | awk -F: '{print $3}')
SECS=$(echo "$OUTPUT" | grep "Duration:" | sed 's^,^:^g' | awk -F: '{print $4}')
echo "DURATION=$(echo "($HRS * 60 * 60) + ($MINS * 60) + $SECS" | bc -l)"
echo "FRAME_RATE=$(echo "$VIDEO" |awk -F\, '{print $5}' | sed 's^ tbr^^g' | sed 's^ ^^g')"
echo "AUDIO_STREAMS=$(echo "$OUTPUT" | grep "Stream " | grep "Audio" | wc -l)"
echo "ASPECT_RATIO=$ASPECT"
echo "WIDTH=$(echo $RESOLUTION | awk -Fx '{print $1}')"
echo "HEIGHT=$(echo $RESOLUTION | awk -Fx '{print $2}')"
echo "DVD_COMPATIBLE=$(echo "$VIDEO" | grep "mpeg2video" | wc -l)"
