/* config.h.  Generated by cmake from config.h.cmake */

#ifndef CONFIG_H
#define CONFIG_H

/* Version number of package */
#define VERSION "${VERSION}"

/* Name of package */
#define PACKAGE "kmediafactory"
#define COPYRIGHT "(C) 2005-2007 Petri Damsten"
#define HOMEPAGE  "http://www.iki.fi/damu/software/kmediafactory/"
#define BUG_EMAIL "petri.damsten@iki.fi"

/* Define if you have libdvdread */
#cmakedefine HAVE_LIBDVDREAD 1

#endif