/* config.h.  Generated by cmake from config.h.cmake */

#ifndef CONFIG_H
#define CONFIG_H

/* Version number of package */
#define VERSION "${VERSION}"

/* Name of package */
#define PACKAGE "kmediafactory"

/* Define if you have libdvdread */
#cmakedefine HAVE_LIBDVDREAD 1

#endif