#!/bin/bash
# Get frame from video for KMediafactory
# Copyright (C) 2006 by Petri Damsten - GPL-2
# Usage:
# frame /media/movies/movie.mpg 00:10:00 /home/user/kmf/image.pnm

SCRIPTS=`dirname $0`
. $SCRIPTS/tools

FFMPEG=`check_executable "ffmpeg" "ffmpeg"`

FILE=$1
TIME=$2
OUTPUT="$3"

rm -f "$OUTPUT"
$FFMPEG -itsoffset -$TIME -i "$FILE" -vcodec ppm -vframes 1 -an -f rawvideo \
    "$OUTPUT"
