#!/bin/bash
# Get video info for KMediafactory
# Copyright (C) 2007 by Petri Damsten - GPL-2
# Usage:
# kmf_info /media/movies/movie.mpg

FFMPEG=`which ffmpeg 2>/dev/null`
if [ $? -eq 0 ]; then
    OUTPUT=`$FFMPEG -i "$1" 2>&1`
    VIDEO=$(echo "$OUTPUT" | grep Stream | grep "Video:")
    AUDIO=$(echo "$OUTPUT" | grep "Stream #0.1" | grep "Audio")
    ASPECT=$(echo "$VIDEO" | awk -FDAR '{print $2}' | awk -F' ' '{print $1}' | sed 's^]^^g' | sed 's^,^^g')
    RESOLUTION=$(echo "$VIDEO" | awk -FVideo: '{print $2}' | awk '{print $3}')
    if [ "$ASPECT" = "4:3" ] ; then
        ASPECT=0
    else
        ASPECT=1
    fi
    HRS=$(echo "$OUTPUT" | grep "Duration:" | awk -F: '{print $2}')
    MINS=$(echo "$OUTPUT" | grep "Duration:" | awk -F: '{print $3}')
    SECS=$(echo "$OUTPUT" | grep "Duration:" | sed 's^,^:^g' | awk -F: '{print $4}')
    echo "DURATION=$(echo "($HRS * 60 * 60) + ($MINS * 60) + $SECS" | bc -l)"
    echo "FRAME_RATE=$(echo "$VIDEO" |awk -F\, '{print $5}' | sed 's^ tbr^^g' | sed 's^ ^^g')"
    echo "AUDIO_STREAMS=$(echo "$OUTPUT" | grep "Stream " | grep "Audio" | wc -l)"
    echo "ASPECT_RATIO=$ASPECT"
    echo "WIDTH=$(echo $RESOLUTION | awk -Fx '{print $1}')"
    echo "HEIGHT=$(echo $RESOLUTION | awk -Fx '{print $2}')"
    echo "DVD_COMPATIBLE=$(echo "$VIDEO" | grep "mpeg2video" | wc -l)"
else
    MPLAYER=`which mplayer 2>/dev/null`
    if [ $? -ne 0 ]; then
        kdialog --caption "KMediaFactory" --icon kmediafactory $EMBED --sorry \
            "Cannot continue because neither mplayer nor ffmpeg were found on your system.\nPlease install one of these."
        exit -1
    else
        OUTPUT=`$MPLAYER -v -vo null -ao null -frames 0 -identify "$1" 2>&1`

        echo "DURATION=$(echo "$OUTPUT" | grep "ID_LENGTH" | sed "s/ID_LENGTH=//g")"
        echo "FRAME_RATE=$(echo "$OUTPUT" | grep "ID_VIDEO_FPS" | sed "s/ID_VIDEO_FPS=//g")"
        echo "AUDIO_STREAMS=$(echo "$OUTPUT" | grep "audio stream" | wc -l)"
        echo "ASPECT_RATIO=$(($(echo "$OUTPUT" | grep "aspect" | sed "s/.*aspect //g" | sed "s/).*//g")-2))"
        echo "WIDTH=$(echo "$OUTPUT" | grep "ID_VIDEO_WIDTH" | sed "s/ID_VIDEO_WIDTH=//g")"
        echo "HEIGHT=$(echo "$OUTPUT" | grep "ID_VIDEO_HEIGHT" | sed "s/ID_VIDEO_HEIGHT=//g")"
        DEMUXER=$(echo "$OUTPUT" | grep "ID_DEMUXER" | sed "s/ID_DEMUXER=//g")
        if [ "$DEMUXER" = "mpegps" ]; then
            echo "DVD_COMPATIBLE=1"
        else
            echo "DVD_COMPATIBLE=0"
        fi
    fi
fi
