execute_process(COMMAND svn info
                COMMAND grep Revision
                COMMAND sed "s/Revision: //"
                WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
                OUTPUT_VARIABLE REVISION
                OUTPUT_STRIP_TRAILING_WHITESPACE)
set(REVISION ".svn${REVISION}")

FILE(WRITE ${CMAKE_BINARY_DIR}/svnrev.h
"/* svnrev.h.  Generated by cmake */
\#define SVNREV \"${REVISION}\"
")
