#!/bin/bash
# Get comment for jpg
# Copyright (C) 2007 by Petri Damsten - GPL-2
# Usage:
# kmf_comment /media/photos/photo.jpg

SCRIPTS=`dirname $0`
. $SCRIPTS/tools

EXIFTIME=`check_executable "exiftime" "exiftime"`

$EXIFTIME -tc "$1" | sed "s/Image Created: //g"
